schema_version = "1.0.0"



id = "secret_paint"
version = "1.7.21"
name = "Secret Paint"
tagline = "Select an object, select a surface, paint"
maintainer = "orencloud"

type = "add-on"


website = "https://orencloud.art/secretpaint"



tags = ["Modeling", "Add Curve"]

blender_version_min = "4.2.0"






license = [
  'SPDX:GPL-3.0-or-later',
]

copyright = ["2022-2024 orencloud"]





[permissions]
network = "Update from GitHub if installed as addon rather than extension"
files = "Export objects and biomes to external blend files"